window.SCU_HUB_DATA = {
  categories: [
    'Study',
    'Research',
    'Online Courses',
    'Campus Life',
    'Engineering',
    'Productivity'
  ],
  sites: [
    { category: 'Study', name: '教务处主页', url: 'https://jwc.scu.edu.cn/' },
    { category: 'Study', name: '本学期课表', url: 'http://zhjw.scu.edu.cn/student/courseSelect/thisSemesterCurriculum/index' },
    { category: 'Study', name: '选课界面', url: 'http://zhjw.scu.edu.cn/student/courseSelect/courseSelect/index' },
    { category: 'Study', name: '空闲教室查询', url: 'http://zhjw.scu.edu.cn/student/teachingResources/freeClassroom/index' },
    { category: 'Study', name: '本学期成绩查询', url: 'http://zhjw.scu.edu.cn/student/integratedQuery/scoreQuery/thisTermScores/index' },
    { category: 'Study', name: '考试安排查看', url: 'http://zhjw.scu.edu.cn/student/examinationManagement/examPlan/index' },
    { category: 'Study', name: '成绩可信证明生成', url: 'http://zhjw.scu.edu.cn/student/integratedQuery/scoreQuery/credibleReportCard/index' },
    { category: 'Study', name: '学生评教', url: 'http://zhjw.scu.edu.cn/student/teachingEvaluation/newEvaluation/index' },
    { category: 'Study', name: '四六级考试报名网', url: 'https://cet-bm.neea.edu.cn/' },
    { category: 'Research', name: '图书馆主页', url: 'https://lib.scu.edu.cn/' },
    { category: 'Research', name: '图书馆书籍检索', url: 'http://opac.scu.edu.cn:8080/' },
    { category: 'Research', name: '超星大雅论文查重', url: 'https://i.chaoxing.com/base?ws=1' },
    { category: 'Research', name: '学术资源网关（校外访问）', url: 'https://lib.scu.edu.cn/xiaowai/xw.html' },
    { category: 'Research', name: 'Web of Science', url: 'https://esource.scu.edu.cn/https/443/cn/clarivate/webofscience/yitlink/wos/woscc/smart-search' },
    { category: 'Research', name: 'ScienceDirect', url: 'https://esource.scu.edu.cn/https/443/com/sciencedirect/www/yitlink/' },
    { category: 'Research', name: 'IEEE', url: 'https://esource.scu.edu.cn/https/443/org/ieee/ieeexplore/yitlink/Xplore/home.jsp' },
    { category: 'Research', name: 'Google Scholar', url: 'https://scholar.google.com/' },
    { category: 'Research', name: 'TeXPage', url: 'https://www.texpage.com/console' },
    { category: 'Research', name: 'Overleaf', url: 'https://cn.overleaf.com/' },
    { category: 'Online Courses', name: '超星学习通', url: 'https://v8.chaoxing.com/' },
    { category: 'Online Courses', name: '雨课堂', url: 'https://www.yuketang.cn/web' },
    { category: 'Online Courses', name: '智慧树', url: 'https://www.zhihuishu.com/' },
    { category: 'Online Courses', name: '爱课程', url: 'https://iclass.scu.edu.cn/stu/#/index' },
    { category: 'Online Courses', name: 'MOOC', url: 'https://www.icourse163.org/' },
    { category: 'Campus Life', name: '校园网', url: 'http://self.scu.edu.cn:8080/selfservice/' },
    { category: 'Campus Life', name: '创在川大', url: 'https://czcd.scu.edu.cn/pt/System/Home/Index' },
    { category: 'Campus Life', name: '网络报修平台', url: 'https://zhhq.scu.edu.cn/znbx/' },
    { category: 'Campus Life', name: '第二课堂', url: 'https://dekt.scu.edu.cn/ccylmp/pages/main/activity/activity' },
    { category: 'Campus Life', name: '财务处', url: 'https://fdinfo.scu.edu.cn/WFManager' },
    { category: 'Campus Life', name: '学工一体化平台', url: 'https://xsc.scu.edu.cn/userhall/sec/page/index' },
    { category: 'Campus Life', name: '学生邮箱', url: 'https://mail.stu.scu.edu.cn/' },
    { category: 'Campus Life', name: '电气工程学院', url: 'https://ee.scu.edu.cn/' },
    { category: 'Campus Life', name: '充电费', url: 'https://payapp.scu.edu.cn/eleFees/' },
    { category: 'Engineering', name: '德州仪器', url: 'https://www.ti.com/' },
    { category: 'Engineering', name: 'Analog', url: 'https://www.analog.com/' },
    { category: 'Engineering', name: '立创商城', url: 'https://www.szlcsc.com/' },
    { category: 'Productivity', name: 'GitHub', url: 'https://github.com/' },
    { category: 'Productivity', name: 'Linux Do', url: 'https://linux.do/' },
    { category: 'Productivity', name: 'LeetCode', url: 'https://leetcode.cn/' },
    { category: 'Productivity', name: 'OpenRouter', url: 'https://openrouter.ai/' },
    { category: 'Productivity', name: 'ChatGPT', url: 'https://chatgpt.com/' },
    { category: 'Productivity', name: 'Claude', url: 'https://claude.ai/' },
    { category: 'Productivity', name: 'Gemini', url: 'https://gemini.google.com/' },
    { category: 'Productivity', name: 'Canva', url: 'https://www.canva.com/' },
    { category: 'Productivity', name: 'Manus', url: 'https://manus.im/app' },
    { category: 'Productivity', name: 'Gmail', url: 'https://mail.google.com/' },
    { category: 'Productivity', name: 'Perplexity', url: 'https://www.perplexity.ai/' },
    { category: 'Productivity', name: 'Notion', url: 'https://www.notion.so/' },
    { category: 'Productivity', name: '腾讯文档', url: 'https://docs.qq.com/' },
    { category: 'Productivity', name: 'Figma', url: 'https://www.figma.com/' },
    { category: 'Productivity', name: 'Draw.io', url: 'https://www.drawio.com/' }
  ]
};
